name: gamepads_android
resolution: workspace
description: Android implementation of gamepads, a Flutter plugin to handle gamepad input across multiple platforms.
version: 0.1.6
publish_to: none

flutter:
  plugin:
    platforms:
      android:
        package: org.flame_engine.gamepads_android
        pluginClass: GamepadsAndroidPlugin

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  gamepads_platform_interface:
    path: ../gamepads_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
